import { TextSkeleton } from '../components/skeleton';
import { useI18n } from '../i18n/i18n';
import { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { styled } from 'styled-components';
import { useAccount, useSaved, languageNames } from '../product/data';
import { supabase } from '../supabase';
import { Page, Wrap, Box, Stack, Button, Notice } from '../product/ui';
const Content=styled.div`h1{font-size:32px;line-height:36px;letter-spacing:-.2px;}.identity{display:flex;align-items:center;gap:20px;margin:28px 0 24px;}.avatar{width:84px;height:84px;flex-shrink:0;display:grid;place-items:center;font:600 32px/36px 'Cormorant Garamond',serif;position:relative;}.avatar img{position:absolute;inset:0;width:84px;height:84px;}.avatar span{position:relative;}h2{font:500 26px/30px 'Cormorant Garamond',serif;}p{font-size:14px;color:var(--st-muted);}.account-title{margin:28px 0 18px;}.row{display:flex;align-items:center;justify-content:space-between;gap:16px;min-height:70px;padding:14px 16px;border:1px solid var(--st-line);border-radius:16px;background:var(--st-surface);}.row strong{font-size:16px;line-height:24px;}.row p{font-size:13px;line-height:20px;}.arrow{font-size:24px;color:var(--st-gold);}`;
export default function Account(){const { t } = useI18n();const{account}=useAccount();const{saved}=useSaved();const navigate=useNavigate();const[profile,setProfile]=useState<{display_name:string;preferred_language:string;onboarding_completed:boolean}|null>(null);const[error,setError]=useState('');const[busy,setBusy]=useState(false);useEffect(()=>{if(!account)return;let alive=true;supabase.from('profiles').select('display_name,preferred_language,onboarding_completed').eq('auth_user_id',account.id).single().then(({data,error})=>{if(alive){if(error)setError('Your profile could not be loaded.');else setProfile(data);}});return()=>{alive=false;};},[account]);return <Page><Wrap style={{maxWidth:620}}><Content><div style={{display:'flex',alignItems:'center',justifyContent:'space-between'}}><h1>{t("Your profile")}</h1><Link to="/onboarding?next=/profile" style={{fontSize:12,color:'var(--st-gold)'}}>{t("Edit")}</Link></div><div className="identity"><div className="avatar"><img src="/figma/profile-avatar.svg" width="84" height="84" alt=""/><span>{profile?.display_name?.[0]?.toUpperCase()||'S'}</span></div><div style={{flex:1,minWidth:0}}>{!profile&&!error?<TextSkeleton lines={2}/>:<><h2>{profile?.display_name||t("Your account")}</h2><p>{t(languageNames[profile?.preferred_language||'en'])} · KRW</p></>}</div></div><Box style={{background:'var(--st-elevated)',borderColor:'var(--st-accent-line)'}}>{!profile&&!error?<TextSkeleton lines={2}/>:<><strong>{profile?.onboarding_completed?t("Your profile is ready"):t("Complete your profile")}</strong><p>{profile?.onboarding_completed?t("Your preferences are saved for your next reading."):t("Add your name and reading preferences to get started.")}</p></>}</Box><h2 className="account-title">{t("Account")}</h2><Stack>{[['/onboarding?next=/profile',t("Personal information"),t("Name, birthday & preferences")],['/onboarding?next=/profile',t("Reading language"),`${t(languageNames[profile?.preferred_language||'en'])} · ${t('Prices in KRW')}`],['/saved',t("Saved readings"),`${saved.length} · ${t('Saved on this device')}`],['/messages',t('Messages'),t('Open your existing messages.')],['/trips',t("Your bookings"),t("Visit requests & preview plans")],['/privacy',t("Privacy & data"),t("How your account and birth details are used")],['/support',t("Help & support"),t("Questions about your reading")]].map(([to,title,sub])=><Link className="row" key={title} to={to}><div><strong>{title}</strong><p>{sub}</p></div><span className="arrow">›</span></Link>)}{error&&<Notice role="alert">{t(error)}</Notice>}<Button $secondary disabled={busy} onClick={async()=>{setBusy(true);const{error}=await supabase.auth.signOut();if(error){setError('Could not sign out. Please try again.');setBusy(false);}else navigate('/');}}>{busy?t("Signing out…"):t("Sign out")}</Button></Stack></Content></Wrap></Page>;}
