import { useEffect, useState, type FormEvent } from 'react';
import { styled } from 'styled-components';
import { useI18n } from '../i18n/i18n';
import { supabase } from '../supabase';
import { Page, Wrap, Field, Button, Notice, Box, Stack } from '../product/ui';
import { TextSkeleton } from '../components/skeleton';
import { safeNotificationPath, type Notification } from '../product/notifications';
type Draft=Omit<Notification,'read_at'> & {status:'draft'|'published';recipient_id:string|null};
const Form=styled.form`display:grid;gap:18px;details{padding:14px;border:1px solid var(--st-line);border-radius:14px;}summary{cursor:pointer;font-size:13px;}details>div{display:grid;gap:14px;padding-top:16px;}.actions{display:flex;flex-wrap:wrap;gap:10px;}.preview{white-space:pre-wrap;overflow-wrap:anywhere;}small{color:var(--st-muted);font-size:12px;line-height:1.6;}`;
export default function AdminNotifications(){
 const {t}=useI18n();const [rows,setRows]=useState<Draft[]>([]);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');
 const [id,setId]=useState('');const [title,setTitle]=useState('');const [body,setBody]=useState('');const [category,setCategory]=useState('update');const [path,setPath]=useState('');const [recipient,setRecipient]=useState('');
 const [translations,setTranslations]=useState<Record<string,{title:string;body:string}>>({});const [confirm,setConfirm]=useState(false);const [limit,setLimit]=useState(30);const [hasMore,setHasMore]=useState(false);
 async function load(){const {data,error}=await supabase.from('sajuteller_notifications').select('*').order('created_at',{ascending:false}).limit(limit+1);if(error)setError('Notifications could not be loaded. Please try again.');else{setRows((data||[]).slice(0,limit));setHasMore((data?.length||0)>limit);}setLoading(false);}
 useEffect(()=>{let alive=true;void supabase.from('sajuteller_notifications').select('*').order('created_at',{ascending:false}).limit(limit+1).then(({data,error})=>{if(!alive)return;if(error)setError('Notifications could not be loaded. Please try again.');else{setRows((data||[]).slice(0,limit));setHasMore((data?.length||0)>limit);}setLoading(false);});return()=>{alive=false;};},[limit]);
 function reset(){setId('');setTitle('');setBody('');setCategory('update');setPath('');setRecipient('');setTranslations({});setConfirm(false);setNotice('');setError('');}
 function edit(row:Draft){setId(row.id);setTitle(row.title);setBody(row.body);setCategory(row.category);setPath(row.action_path||'');setRecipient(row.recipient_id||'');setTranslations(Object.fromEntries(Object.entries(row.translations).map(([key,value])=>[key,{title:value.title||'',body:value.body||''}])));setConfirm(false);setNotice('');window.scrollTo({top:0,behavior:'instant'});}
 async function save(publish=false){
  if(busy)return;if(!title.trim()||!body.trim()){setError('A title and message are required.');return;}
  if(path&&!safeNotificationPath(path)){setError('Use an internal page path, such as /experiences.');return;}
  if(recipient&&!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(recipient)){setError('Enter a valid user ID or leave the audience as everyone.');return;}
  setBusy(true);setError('');setNotice('');
  const payload={title:title.trim(),body:body.trim(),category,action_path:path||null,recipient_id:recipient||null,translations,status:publish?'published':'draft',published_at:publish?new Date().toISOString():null};
  try{const query=id?supabase.from('sajuteller_notifications').update(payload).eq('id',id).eq('status','draft'):supabase.from('sajuteller_notifications').insert(payload);const {data,error}=await query.select('id').single();if(error||!data)throw error;setId(data.id);setConfirm(false);setNotice(publish?'Published to the in-app inbox.':'Draft saved.');await load();if(publish){setId('');setTitle('');setBody('');setPath('');setRecipient('');setTranslations({});}}
  catch{setError('Your changes could not be saved. Please try again.');}finally{setBusy(false);}
 }
 async function withdraw(row:Draft){setBusy(true);setError('');const {data,error}=await supabase.from('sajuteller_notifications').update({status:'draft',published_at:null}).eq('id',row.id).select('id');if(error||!data?.length)setError('Your changes could not be saved. Please try again.');else{setNotice('Announcement withdrawn.');await load();}setBusy(false);}
 function submit(event:FormEvent){event.preventDefault();void save();}
 return <Page><Wrap><Stack><header><h1>{t('SajuTeller announcements')}</h1><p>{t('Create updates and offers for the in-app inbox.')}</p></header>{error&&<Notice role="alert">{t(error)} <button onClick={()=>void load()}>{t('Retry')}</button></Notice>}{notice&&<Notice role="status">{t(notice)}</Notice>}
 <Box><Form onSubmit={submit}><Field>{t('Title')}<input maxLength={160} required value={title} onChange={e=>{setTitle(e.target.value);setConfirm(false);}}/></Field><Field>{t('Message')}<textarea maxLength={5000} required value={body} onChange={e=>{setBody(e.target.value);setConfirm(false);}}/></Field><Field>{t('Category')}<select value={category} onChange={e=>{setCategory(e.target.value);setConfirm(false);}}><option value="update">{t('Service update')}</option><option value="offer">{t('Offer')}</option></select></Field><Field>{t('Link to page')}<input placeholder="/experiences" value={path} onChange={e=>{setPath(e.target.value);setConfirm(false);}}/></Field><Field>{t('Recipient user ID (optional)')}<input value={recipient} onChange={e=>{setRecipient(e.target.value);setConfirm(false);}}/></Field><small>{t('Leave blank to reach all signed-in users. Offers respect inbox preferences.')}</small>
 <details><summary>{t('Translations (optional)')}</summary><div>{[['ko','한국어'],['zh','简体中文'],['ja','日本語'],['es','Español']].map(([code,label])=><div key={code}><Field>{label} — {t('Title')}<input maxLength={160} value={translations[code]?.title||''} onChange={e=>{setTranslations(old=>({...old,[code]:{body:old[code]?.body||'',title:e.target.value}}));setConfirm(false);}}/></Field><Field>{label} — {t('Message')}<textarea maxLength={5000} value={translations[code]?.body||''} onChange={e=>{setTranslations(old=>({...old,[code]:{title:old[code]?.title||'',body:e.target.value}}));setConfirm(false);}}/></Field></div>)}</div></details>
 <div className="actions"><Button disabled={busy}>{t('Save draft')}</Button><Button type="button" $secondary disabled={busy||!title.trim()||!body.trim()} onClick={()=>setConfirm(true)}>{t('Preview publication')}</Button>{id&&<Button type="button" $secondary onClick={reset}>{t('New announcement')}</Button>}</div>
 {confirm&&<Box><h2>{t('Preview publication')}</h2><strong>{title}</strong><p className="preview">{body}</p><p>{t(recipient?'Audience: selected user':'Audience: all signed-in users')}</p><p>{t('This inbox does not send email or push notifications.')}</p><div className="actions" style={{marginTop:16}}><Button type="button" disabled={busy} onClick={()=>void save(true)}>{t('Publish to inbox')}</Button><Button type="button" $secondary onClick={()=>setConfirm(false)}>{t('Cancel')}</Button></div></Box>}
 </Form></Box><h2>{t('Announcements')}</h2>{loading?<TextSkeleton/>:rows.length?rows.map(row=><Box key={row.id}><p>{t(row.status==='draft'?'Draft':'Published')} / {t(row.category==='offer'?'Offer':'Service update')}</p><h3>{row.title}</h3><p style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{row.body}</p><Button $secondary disabled={busy} style={{marginTop:14}} onClick={()=>row.status==='draft'?edit(row):void withdraw(row)}>{t(row.status==='draft'?'Edit draft':'Withdraw')}</Button></Box>):<p>{t('No announcements yet.')}</p>}{hasMore&&<Button $secondary onClick={()=>setLimit(v=>v+30)}>{t('Load more')}</Button>}</Stack></Wrap></Page>;
}
