import { useSearchParams } from 'react-router-dom';
import { styled } from 'styled-components';
import { AdjustmentsHorizontalIcon, MagnifyingGlassIcon, MapPinIcon } from '@heroicons/react/24/outline';
import { useState } from 'react';
import { filterStudios, languageNames, topics, useStudios } from '../product/data';
import { ButtonLink, Chip, Chips, Empty, ExperienceCard, Field, LoadingCards, Notice, Page, Wrap } from '../product/ui';
import { useI18n } from '../i18n/i18n';
const Catalog=styled.div`display:grid;gap:24px;.heading{display:flex;align-items:center;justify-content:space-between;gap:12px;}.heading h1{font:600 34px/1.15 'Cormorant Garamond',serif;letter-spacing:-.6px;margin:0;}.heading a{min-height:44px;padding:10px 14px;font-size:12px;border-radius:999px;} .intro{font-size:14px;line-height:1.65;color:var(--st-muted);margin-top:-12px;}.tools{display:grid;gap:8px;}.search{display:flex;align-items:center;border:1px solid var(--st-line);background:var(--st-surface);border-radius:999px;padding:0 8px 0 16px;gap:8px;}.search svg{width:19px;flex:none;color:var(--st-muted);}.search input{width:100%;min-width:0;padding:14px 0;border:0;outline-offset:3px;background:none;color:var(--st-ink);font-size:14px;}.search button{border:0;border-radius:50%;background:var(--st-elevated);color:var(--st-ink);width:44px;height:44px;display:grid;place-items:center;cursor:pointer;}.section-label{display:flex;justify-content:space-between;gap:16px;align-items:center;}.section-label h2{font-size:19px;font-weight:600;letter-spacing:-.3px;}.count{font-size:12px;color:var(--st-muted);}.list{display:grid;grid-template-columns:minmax(0,1fr);gap:24px;}.list>[data-experience-card]{content-visibility:auto;contain-intrinsic-size:auto 485px;}.clear{border:0;background:none;color:var(--st-gold);font-size:12px;min-height:44px;cursor:pointer;}`;
const Filters=styled.div`padding:20px;background:var(--st-surface);border:1px solid var(--st-line);border-radius:20px;display:grid;gap:18px;`;
export default function Experiences(){
 const{t,language}=useI18n();const{studios,loading,error,reload}=useStudios();const[params,setParams]=useSearchParams();const[filters,setFilters]=useState(false);const found=filterStudios(studios,params);
 const set=(key:string,v:string)=>setParams(old=>{const n=new URLSearchParams(old);if(v)n.set(key,v);else n.delete(key);return n;});const areas=[...new Set(studios.map(s=>s.neighborhood))].sort();const active=['area','language','budget'].filter(k=>params.get(k)).length;
 return <Page><Wrap><Catalog><header className="heading"><h1>{t('Experiences')}</h1><ButtonLink to="/map" $secondary><MapPinIcon/>{t('Map')}</ButtonLink></header><p className="intro">{t('A local reader. Your language. A little clarity.')}</p><div className="tools"><form className="search" onSubmit={e=>{e.preventDefault();set('q',String(new FormData(e.currentTarget).get('q')||''));}}><MagnifyingGlassIcon/><input name="q" key={params.get('q')} defaultValue={params.get('q')||''} placeholder={t('Studio, neighborhood, or topic')} aria-label={t('Search experiences')}/><button aria-label={t('Search')}><MagnifyingGlassIcon/></button></form><Chips aria-label={t('Reading topics')}>{topics.map(topic=><Chip key={topic.id} $active={(params.get('topic')||'all')===topic.id} aria-pressed={(params.get('topic')||'all')===topic.id} onClick={()=>set('topic',topic.id)}>{t(topic.label)}</Chip>)}<Chip onClick={()=>setFilters(v=>!v)} aria-expanded={filters} aria-controls="experience-filters"><AdjustmentsHorizontalIcon width={16}/>{t('Filters')}{active?` (${active})`:''}</Chip></Chips>{filters&&<Filters id="experience-filters"><Field>{t('Neighborhood')}<select value={params.get('area')||''} onChange={e=>set('area',e.target.value)}><option value="">{t('Anywhere in Seoul')}</option>{areas.map(a=><option key={a}>{a}</option>)}</select></Field><Field>{t('Reading language')}<select value={params.get('language')||''} onChange={e=>set('language',e.target.value)}><option value="">{t('Any language')}</option>{Object.keys(languageNames).map(k=><option value={k} key={k}>{new Intl.DisplayNames([language],{type:'language'}).of(k)}</option>)}</select></Field><Field>{t('Price per person')}<select value={params.get('budget')||''} onChange={e=>set('budget',e.target.value)}><option value="">{t('Any budget')}</option>{[50000,80000,120000].map(n=><option value={n} key={n}>{t('Up to')} ₩{n.toLocaleString(language)}</option>)}</select></Field><Field>{t('Sort by')}<select value={params.get('sort')||''} onChange={e=>set('sort',e.target.value)}><option value="">{t('Featured first')}</option><option value="price">{t('Lowest price')}</option><option value="duration">{t('Shortest session')}</option></select></Field></Filters>}</div>
 {studios.some(s=>s.demo_chat_enabled)&&<Notice><strong>{t('Meet our demo studios')}</strong><p style={{margin:'8px 0 14px'}}>{t('Try a conversation with an automated host. No real booking or payment.')}</p><ButtonLink to={`/business/${studios.find(s=>s.demo_chat_enabled)!.id}`} $secondary>{t('Try demo chat')}</ButtonLink></Notice>}
 {params.get('matched')&&<Notice>{t('Language support varies by studio. Check the details before booking.')}</Notice>}<div className="section-label"><h2>{t('Find your reading')}</h2><span className="count" aria-live="polite">{loading?t('Loading…'):found.length} {t('experiences')}</span></div>{params.size>0&&<button className="clear" onClick={()=>setParams({})}>{t('Clear filters')}</button>}
 {error?<Notice role="alert">{t(error)} <button onClick={reload}>{t('Try again')}</button></Notice>:loading?<LoadingCards/>:found.length?<div className="list">{found.map(s=><ExperienceCard key={s.id} studio={s}/>)}</div>:<Empty title={t('No experiences found')} body={t('Try another neighborhood, language, or budget.')} action={t('See all experiences')}/>}
 {studios.some(s=>s.is_mock)&&<Notice>{t('Preview collection. Demo chat is available on labeled studios; reservations are illustrative.')}</Notice>}<ButtonLink to="/find-my-reading" $secondary>{t('Help me choose a reading')}</ButtonLink></Catalog></Wrap></Page>;
}
