import { useSearchParams } from 'react-router-dom';
import { styled } from 'styled-components';
import { AdjustmentsHorizontalIcon, MagnifyingGlassIcon, MapPinIcon } from '@heroicons/react/24/outline';
import { useState } from 'react';
import { filterStudios, languageNames, topics, useStudios } from '../product/data';
import { Button, ButtonLink, Chip, Chips, Empty, Eyebrow, ExperienceCard, Field, Grid, Lead, LoadingCards, Notice, Page, Wrap } from '../product/ui';
const Search=styled.form`display:flex;gap:10px;margin:24px 0 12px;label{display:flex;align-items:center;background:white;border:1px solid var(--st-line);border-radius:14px;flex:1;padding:0 14px;min-width:0;svg{width:19px;flex-shrink:0;color:var(--st-muted);}input{width:100%;min-width:0;border:0;background:transparent;padding:15px 10px;outline-offset:-2px;font-size:14px;}}button{padding:12px 15px;}`;
const Filters=styled.div`background:#efede8;border-radius:18px;padding:18px;display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px;margin:8px 0 24px;@media(max-width:700px){grid-template-columns:1fr 1fr;}`;
export default function Experiences(){const{studios,loading,error,reload}=useStudios();const[params,setParams]=useSearchParams();const[filters,setFilters]=useState(false);const found=filterStudios(studios,params);const set=(key:string,v:string)=>setParams(old=>{const n=new URLSearchParams(old);if(v)n.set(key,v);else n.delete(key);return n;});const areas=[...new Set(studios.map(s=>s.neighborhood))].sort();const activeFilters=['area','language','budget'].filter(k=>params.get(k)).length;return <Page><Wrap><Eyebrow><MapPinIcon/>Seoul experiences</Eyebrow><h1>Find your kind<br/>of discovery.</h1><Lead>A traditional reader, a new perspective, a story to take home.</Lead><Search onSubmit={e=>{e.preventDefault();const q=new FormData(e.currentTarget).get('q') as string;set('q',q);}}><label><MagnifyingGlassIcon/><input name="q" key={params.get('q')} defaultValue={params.get('q')||''} placeholder="Studio, neighborhood, or topic" aria-label="Search experiences"/></label><Button type="submit">Search</Button></Search><Chips aria-label="Reading topics">{topics.map(t=><Chip key={t.id} $active={(params.get('topic')||'all')===t.id} onClick={()=>set('topic',t.id)}>{t.label}</Chip>)}<Chip onClick={()=>setFilters(v=>!v)} aria-expanded={filters} aria-controls="experience-filters"><AdjustmentsHorizontalIcon width={15} style={{verticalAlign:'middle',marginRight:6}}/>Filters{activeFilters?` (${activeFilters})`:''}</Chip></Chips>{filters&&<Filters id="experience-filters"><Field>Neighborhood<select value={params.get('area')||''} onChange={e=>set('area',e.target.value)}><option value="">Anywhere in Seoul</option>{areas.map(a=><option key={a}>{a}</option>)}</select></Field><Field>Reading language<select value={params.get('language')||''} onChange={e=>set('language',e.target.value)}><option value="">Any language</option>{Object.entries(languageNames).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></Field><Field>Price per person<select value={params.get('budget')||''} onChange={e=>set('budget',e.target.value)}><option value="">Any budget</option><option value="50000">Up to ₩50,000</option><option value="80000">Up to ₩80,000</option><option value="120000">Up to ₩120,000</option></select></Field><Field>Sort by<select value={params.get('sort')||''} onChange={e=>set('sort',e.target.value)}><option value="">Featured first</option><option value="price">Lowest price</option><option value="duration">Shortest session</option></select></Field></Filters>}
{params.get('matched')&&<Notice>Based on your preferences. Language support can mean a fluent reader, conversational ability, or AI interpretation—check each experience.</Notice>}
<div style={{display:'flex',alignItems:'center',justifyContent:'space-between',margin:'14px 0 22px',gap:12}}><p style={{fontSize:12,color:'var(--st-muted)'}} aria-live="polite">{loading?'Loading…':`${found.length} experiences to explore`}</p>{params.size>0&&<Button $secondary onClick={()=>setParams({})}>Clear filters</Button>}</div>
{error?<Notice role="alert">{error} <button onClick={reload}>Try again</button></Notice>:loading?<LoadingCards/>:found.length?<Grid>{found.map(s=><ExperienceCard key={s.id} studio={s}/>)}</Grid>:<Empty title="A little more room to explore?" body="There are no experiences with this combination yet. Try another neighborhood, language, or budget." to="/experiences" action="See all experiences"/>}
{studios.length>0&&studios.every(s=>s.is_mock)&&<Notice style={{marginTop:28}}>This is a preview collection of sample studios. Prices, photos, and availability illustrate the experience; these studios cannot accept reservations.</Notice>}<ButtonLink to="/find-my-reading" $secondary style={{marginTop:20}}>Help me choose a reading</ButtonLink></Wrap></Page>;}
