import { useEffect, useRef, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { styled } from 'styled-components';
import { ArrowLeftIcon, ArrowUpRightIcon, ChatBubbleLeftRightIcon, ChevronLeftIcon, ChevronRightIcon, ClockIcon, HeartIcon, LanguageIcon, MapPinIcon, ShareIcon, ShieldCheckIcon, UsersIcon } from '@heroicons/react/24/outline';
import { supabase } from '../supabase';
import { money, supportLabel, useSaved, useStudios, type Review, type Service } from '../product/data';
import { Box, Button, ButtonLink, Empty, Field, LoadingCards, Notice, Page, Wrap } from '../product/ui';
import { useI18n } from '../i18n/i18n';
type Reader={id:string;display_name:string;display_name_ko:string;title:string;bio:string;bio_i18n?:Record<string,string>;avatar_url:string|null;years_experience:number|null};
const Detail=styled.div`display:grid;gap:28px;.toolbar{display:flex;justify-content:space-between;gap:12px;}.toolbar>div{display:flex;gap:8px;}.icon-button{width:44px;height:44px;border:1px solid var(--st-line);border-radius:50%;background:var(--st-surface);color:var(--st-ink);display:grid;place-items:center;cursor:pointer;}.icon-button svg{width:20px;height:20px;}.tags{display:flex;gap:7px;flex-wrap:wrap;}.tag{border-radius:999px;background:var(--st-elevated);color:var(--st-gold);padding:7px 10px;font-size:11px;line-height:1.4;}.heading h1{font:600 36px/1.1 'Cormorant Garamond',serif;letter-spacing:-.5px;margin:14px 0;overflow-wrap:anywhere;}.heading p{font-size:14px;line-height:1.6;color:var(--st-muted);}.facts{background:var(--st-surface);border-radius:20px;padding:20px;display:grid;gap:22px;}.fact{display:flex;align-items:flex-start;gap:14px;}.fact>svg{width:22px;height:22px;flex:none;color:var(--st-gold);}.fact strong{display:block;font-size:13px;font-weight:600;margin-bottom:6px;}.fact p{font-size:13px;line-height:1.6;color:var(--st-muted);}.section{display:grid;gap:16px;}.section h2{font-size:21px;font-weight:600;letter-spacing:-.3px;}.section p,.section li{font-size:14px;line-height:1.7;color:var(--st-muted);}.section ul{padding-left:20px;display:grid;gap:12px;}.reader{display:flex;align-items:center;gap:14px;}.reader img{width:56px;height:56px;object-fit:cover;border-radius:50%;background:var(--st-accent);}.reader strong{font-size:16px;font-weight:600;}.reader p{font-size:12px;}.map-link{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:20px;background:var(--st-elevated);border-radius:18px;font-size:13px;line-height:1.6;}.map-link svg{width:20px;flex:none;}.session{padding:22px;border:1px solid var(--st-accent-line);background:var(--st-surface);border-radius:22px;display:grid;gap:18px;}.price{font-size:27px;font-weight:600;color:var(--st-gold);}.price small{font-size:12px;color:var(--st-muted);font-weight:400;}.chat{width:100%;border-radius:999px;}.notice{font-size:12px;color:var(--st-muted);line-height:1.6;}`;
const Gallery=styled.div`position:relative;border-radius:24px;overflow:hidden;background:var(--st-accent);.track{display:flex;overflow:auto;scroll-snap-type:x mandatory;scrollbar-width:none;}.slide{width:100%;flex:0 0 100%;aspect-ratio:1;scroll-snap-align:start;}.slide img{width:100%;height:100%;object-fit:cover;}.gallery-controls{position:absolute;bottom:14px;left:14px;right:14px;display:flex;align-items:center;justify-content:space-between;pointer-events:none;}.gallery-controls button{pointer-events:auto;border:1px solid #ffffff30;border-radius:50%;background:#130a1bd9;color:var(--st-ink);width:44px;height:44px;display:grid;place-items:center;cursor:pointer;}.gallery-controls button:disabled{opacity:.35;cursor:default;}svg{width:20px;height:20px;}.counter{font-size:12px;border-radius:999px;background:#130a1bd9;color:var(--st-ink);padding:9px 12px;}`;
const Actions=styled.div`position:fixed;bottom:0;left:50%;transform:translateX(-50%);width:min(100%,var(--st-app-width));z-index:90;display:flex;align-items:center;gap:12px;background:var(--st-elevated);border-top:1px solid var(--st-line);padding:12px 16px calc(12px + env(safe-area-inset-bottom));.price{flex:1;min-width:0;font-size:11px;color:var(--st-muted);line-height:1.5;}.price strong{display:block;font-size:18px;color:var(--st-ink);}.book{border-radius:999px;max-width:65%;font-size:13px;text-align:center;}`;
export default function Experience(){
 const{t,language}=useI18n();const{id}=useParams();const{studios,loading,error,reload}=useStudios();const studio=studios.find(s=>s.id===id||s.slug===id);const{saved,toggle}=useSaved();
 const[services,setServices]=useState<Service[]>([]);const[reviews,setReviews]=useState<Review[]>([]);const[reader,setReader]=useState<Reader|null>(null);const[serviceId,setServiceId]=useState('');const[detailsError,setDetailsError]=useState('');const[detailsLoading,setDetailsLoading]=useState(true);const[photo,setPhoto]=useState(0);const[notice,setNotice]=useState('');const[retry,setRetry]=useState(0);const gallery=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(!studio)return;let alive=true;setDetailsLoading(true);setDetailsError('');setServices([]);setReader(null);setReviews([]);setPhoto(0);setNotice('');
 Promise.all([supabase.from('studio_services').select('id,studio_id,name,description,duration_minutes,price,max_guests,requires_birth_date,birth_time_recommended').eq('studio_id',studio.id).eq('active',true).order('sort_order'),supabase.from('studio_reviews').select('id,reviewer_display_name,rating,body,title,is_mock,verified_booking').eq('studio_id',studio.id).eq('status','published').eq('is_mock',false).limit(6),supabase.from('studio_practitioners').select('id,display_name,display_name_ko,title,bio,bio_i18n,avatar_url,years_experience').eq('studio_id',studio.id).eq('is_active',true).order('is_primary',{ascending:false}).limit(1).maybeSingle()]).then(([a,b,c])=>{if(!alive)return;if(a.error||b.error||c.error)setDetailsError('Some reading details could not be loaded. Please try again.');setServices(a.data||[]);setServiceId(a.data?.[0]?.id||'');setReviews(b.data||[]);setReader(c.data);setDetailsLoading(false);}).catch(()=>{if(alive){setDetailsError('Some reading details could not be loaded. Please try again.');setDetailsLoading(false);}});return()=>{alive=false;};},[studio,retry]);
 if(loading)return <Page><Wrap><LoadingCards/></Wrap></Page>;
 if(error)return <Page><Wrap><Notice role="alert">{t(error)}<Button onClick={reload}>{t('Retry')}</Button></Notice></Wrap></Page>;
 if(!studio)return <Page><Wrap><Empty title={t('This reading has moved')} body={t('Explore the current collection to find your next reading.')} action={t('Explore experiences')}/></Wrap></Page>;
 const name=language==='ko'&&studio.name_ko?studio.name_ko:studio.name;const service=services.find(s=>s.id===serviceId);const destination=`/business/${studio.id}/booking?service=${serviceId}`;
 const images=[...studio.studio_images].sort((a,b)=>a.sort_order-b.sort_order);if(!images.length)images.push({image_url:'/figma/reading-atmosphere.svg',alt_text:name,sort_order:0});
 const move=(index:number)=>{const g=gallery.current;if(g)g.scrollTo({left:g.clientWidth*index,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});};
 async function share(){try{if(navigator.share)await navigator.share({title:name,url:location.href});else{await navigator.clipboard.writeText(location.href);setNotice('Link copied');}}catch(e){if(!(e instanceof DOMException&&e.name==='AbortError'))setNotice('Could not share. Copy the page address instead.');}}
 return <Page style={{paddingTop:20,paddingBottom:116}}><Wrap><Detail><div className="toolbar"><Link className="icon-button" to="/experiences" aria-label={t('Back to experiences')}><ArrowLeftIcon/></Link><div><button className="icon-button" aria-label={t('Share')} onClick={()=>void share()}><ShareIcon/></button><button className="icon-button" aria-label={t(saved.includes(studio.id)?'Unsave':'Save')} aria-pressed={saved.includes(studio.id)} onClick={()=>toggle(studio.id)}><HeartIcon fill={saved.includes(studio.id)?'currentColor':'none'}/></button></div></div>
 <Gallery aria-label={t('Studio photos')}><div className="track" ref={gallery} onScroll={e=>{const g=e.currentTarget;setPhoto(Math.round(g.scrollLeft/g.clientWidth));}}>{images.map((img,i)=><div className="slide" key={i}><img src={img.image_url} alt={studio.is_mock?t('Illustrative studio photo'):img.alt_text||name} loading={i?'lazy':'eager'} onError={e=>{if(!e.currentTarget.src.endsWith('/figma/reading-atmosphere.svg'))e.currentTarget.src='/figma/reading-atmosphere.svg';}}/></div>)}</div>{images.length>1&&<div className="gallery-controls"><button disabled={!photo} onClick={()=>move(photo-1)} aria-label={t('Previous photo')}><ChevronLeftIcon/></button><span className="counter" aria-live="polite">{photo+1} / {images.length}</span><button disabled={photo===images.length-1} onClick={()=>move(photo+1)} aria-label={t('Next photo')}><ChevronRightIcon/></button></div>}</Gallery>
 <header className="heading"><div className="tags"><span className="tag">{t(studio.modalities.includes('tarot')?'Tarot reading':'Traditional Saju')}</span><span className="tag">{t('Private session')}</span>{studio.is_mock?<span className="tag">{t(studio.demo_chat_enabled?'Demo chat available':'Preview studio')}</span>:studio.verified&&<span className="tag">{t('Verified studio')}</span>}</div><h1>{name}</h1><p>{studio.tagline_i18n?.[language]||studio.tagline}</p></header>
 {studio.is_mock&&<Notice>{t(studio.demo_chat_enabled?'Demo business with an automated host. Details are illustrative; no real booking or payment.':'Preview studio. Details and photos are illustrative; this studio cannot accept reservations or messages.')}</Notice>}
 {studio.demo_chat_enabled&&<ButtonLink className="chat" to={`/messages?studio=${studio.id}`}><ChatBubbleLeftRightIcon/>{t('Try demo chat')}</ButtonLink>}
 <div className="facts"><div className="fact"><ClockIcon/><div><strong>{t('Duration')}</strong><p>{service?.duration_minutes||studio.min_duration_minutes} {t('minutes')}</p></div></div><div className="fact"><UsersIcon/><div><strong>{t('Guests')}</strong><p>{t('Up to')} {service?.max_guests||studio.max_guests}</p></div></div><div className="fact"><LanguageIcon/><div><strong>{t('Reading language')}</strong>{studio.studio_languages.map(l=><p key={l.language_code}>{new Intl.DisplayNames([language],{type:'language'}).of(l.language_code)} — {t(supportLabel(l.support_type))}</p>)}</div></div><div className="fact"><MapPinIcon/><div><strong>{t('Location')}</strong><p>{studio.neighborhood}, {t('Seoul')}</p><p>{studio.is_mock?t('Illustrative location in Seoul'):studio.address_line1}</p></div></div></div>
 <section className="section"><h2>{t('About this experience')}</h2><p>{studio.description_i18n?.[language]||studio.description}</p></section>
 <section className="section"><h2>{t('Before your visit')}</h2><Box><ul><li>{t('Bring your birth date and time, if known, and one or two questions.')}</li><li>{t('AI interpretation may make mistakes. Confirm important meanings with your reader.')}</li><li>{t('Requests are reviewed by the studio. Confirm the final price and cancellation terms before paying.')}</li></ul><Link to="/refund-policy" style={{display:'inline-flex',alignItems:'center',gap:8,marginTop:18,fontSize:13,color:'var(--st-gold)'}}><ShieldCheckIcon width={18}/>{t('Cancellation policy')}</Link></Box></section>
 <section className="section"><h2>{t(studio.demo_chat_enabled?'Meet your demo host':'Meet your reader')}</h2>{studio.demo_chat_enabled&&<p>{t('Ask about pricing, languages, or how to prepare. Replies are automated for this demo.')}</p>}{detailsLoading?<p role="status">{t('Loading…')}</p>:reader?<><div className="reader"><img src={reader.avatar_url||'/figma/reader-avatar.svg'} alt="" onError={e=>{e.currentTarget.src='/figma/reader-avatar.svg';}}/><div><strong>{language==='ko'&&reader.display_name_ko?reader.display_name_ko:reader.display_name}</strong><p>{t('Saju practitioner')}{reader.years_experience!==null?` / ${reader.years_experience} ${t('years of practice')}`:''}</p></div></div><p>{reader.bio_i18n?.[language]||reader.bio}</p></>:<p>{t('Reader details will be shared by the studio.')}</p>}
 {studio.is_mock&&!studio.demo_chat_enabled?<Button $secondary className="chat" onClick={()=>setNotice('Preview studios cannot receive messages. Choose a live studio when available.')}><ChatBubbleLeftRightIcon/>{t('Chat with the business')}</Button>:<ButtonLink $secondary className="chat" to={`/messages?studio=${studio.id}`}><ChatBubbleLeftRightIcon/>{t('Chat with the business')}</ButtonLink>}{notice&&<Notice role="status">{t(notice)}</Notice>}</section>
 <section className="section"><h2>{t('What you can explore')}</h2><div className="tags">{studio.specialties.map(topic=><span className="tag" key={topic}>{t(topic.replaceAll('_',' ').replace(/^./,c=>c.toUpperCase()))}</span>)}</div></section>
 <section className="section"><h2>{t('Traveler reviews')}</h2>{reviews.length?reviews.map(r=><Box key={r.id}><p>★ {r.rating} {r.verified_booking&&t('Verified booking')}</p><p>{r.body}</p><p>{r.reviewer_display_name}</p></Box>):<p>{t('No traveler reviews to share yet.')}</p>}</section>
 <section className="section"><h2>{t('Getting there')}</h2><Link className="map-link" to={`/map?studio=${studio.id}`}><span>{studio.neighborhood}, {t('Seoul')}<br/>{t('View reading map')}</span><ArrowUpRightIcon/></Link>{!studio.is_mock&&studio.nearest_station&&<p>{studio.nearest_station} / {studio.station_walk_minutes} {t('minutes on foot')}</p>}</section>
 <section className="session"><h2>{t('Choose your session')}</h2>{detailsError&&<Notice role="alert">{t(detailsError)} <button onClick={()=>setRetry(x=>x+1)}>{t('Retry')}</button></Notice>}<Field>{t('Session')}<select value={serviceId} onChange={e=>setServiceId(e.target.value)} disabled={detailsLoading||!services.length}>{services.map(s=><option key={s.id} value={s.id}>{t(s.name)} / {s.duration_minutes} {t('minutes')}</option>)}</select></Field><div className="price">{money(service?.price||studio.base_price,language)} <small>{t('per person')}</small></div>{service&&<p className="notice">{t(service.description)}</p>}<p className="notice">{t(studio.is_mock?'No payment or reservation will be made.':'Your preferred time is not confirmed until the studio accepts your request.')}</p></section>
 </Detail>{service&&<Actions data-booking-action><div className="price">{t('From')}<strong>{money(service.price,language)}</strong></div><ButtonLink className="book" to={destination}>{t(studio.is_mock?'Preview visit':'Request a time')}</ButtonLink></Actions>}</Wrap></Page>;
}
