import {useState} from 'react';
import {styled} from 'styled-components';
import {Page,Wrap,Eyebrow,Lead,Field,Stack,InlineLink} from '../product/ui';
const questions=[
['What is Saju?','Saju is a Korean tradition that interprets the year, month, day, and hour of your birth. A reader uses these four pillars to start a conversation about personality, relationships, work, and timing. It is a cultural practice, not a scientifically proven prediction.'],
['Is this suitable for a first-time visitor?','Yes. Start with the beginner’s guide or take the three-question experience finder. You do not need to know Korean or share birth information to browse.'],
['What does Preview studio mean?','Preview studios are sample listings that show how the marketplace will work. Their photos are illustrative. You can save them or create a preview plan on this device, but it is not a booking and nobody is contacted.'],
['Does sending a request confirm my visit?','No. For real studios, you can request a preferred date and time. The status stays Requested until the host confirms it. There is no payment or immediate reservation in this flow.'],
['How do I cancel?','Open Trips to cancel a request while it is still Requested. For a confirmed visit, contact the studio using its listing details to discuss changes and its terms. Preview plans can simply be removed from this device.'],
['Will the reader speak my language?','Check the language format on each listing. Native or conversational support means the reader speaks that language. AI interpreter support is different and may make mistakes. Confirm the exact format with a real host before your visit.'],
['Do I need my exact birth time?','An exact birth time helps a traditional four-pillars reading. If you do not know it, tell the reader rather than guessing. You do not need to enter birth details to use our experience finder or request a visit.'],
['Where are my saved places and preview plans stored?','They are saved in this browser on this device. Clearing browser data removes them. Real booking requests are linked to your signed-in account.'],
['How can my business join?','Open Become a host, sign in, and submit your studio and language details. The application is saved for review; submitting it does not automatically publish a listing.']
];
const Item=styled.details`background:white;border:1px solid var(--st-line);border-radius:16px;padding:0 20px;summary{cursor:pointer;min-height:64px;padding:22px 0;font-size:14px;font-weight:650;line-height:1.5;}p{padding:0 0 22px;color:var(--st-muted);font-size:14px;line-height:1.7;}`;
export default function FAQ(){const[term,setTerm]=useState('');const filtered=questions.filter(q=>q.join(' ').toLowerCase().includes(term.toLowerCase()));return <Page><Wrap style={{maxWidth:760}}><Eyebrow>Good questions</Eyebrow><h1>Before you go.</h1><Lead>Practical answers for curious travelers.</Lead><Field style={{marginBottom:24}}>Search questions<input value={term} onChange={e=>setTerm(e.target.value)} placeholder="Try languages, birth time, or booking" type="search"/></Field><Stack>{filtered.map(([q,a])=><Item key={q}><summary>{q}</summary><p>{a}</p></Item>)}{!filtered.length&&<Lead>No matching questions. Try a different word.</Lead>}</Stack><InlineLink to="/support" style={{marginTop:24}}>More help →</InlineLink></Wrap></Page>}
