import { Link } from 'react-router-dom';
import { styled } from 'styled-components';
import { MagnifyingGlassIcon, ArrowRightIcon } from '@heroicons/react/24/outline';
import { useStudios } from '../product/data';
import { ButtonLink, Empty, ExperienceCard, Notice, Wrap } from '../product/ui';
const Root=styled.div`padding:22px 0 32px;overflow:hidden;`;
const Hero=styled.section`
  position:relative;height:230px;border-radius:20px;overflow:hidden;
  .art{position:absolute;right:0;top:0;width:358px;height:230px;max-width:none;}
  .copy{position:relative;padding:20px 16px;}h1{font:600 46px/50px 'Cormorant Garamond',serif;letter-spacing:-.5px;max-width:320px;}p{font-size:16px;line-height:24px;color:var(--st-muted);margin-top:18px;}
  @media(min-width:700px){height:320px;background:var(--st-surface);.art{top:45px;right:50px;transform:scale(1.5);transform-origin:right center;}.copy{padding:54px 40px;}h1{font-size:64px;line-height:64px;max-width:520px;}p{margin-top:24px;}}
  @media(max-width:370px){h1{font-size:41px;line-height:46px;}}
`;
const Intro=styled.div`display:grid;gap:16px;.primary{width:100%;height:52px;border-radius:12px;margin-top:2px;}@media(min-width:850px){grid-template-columns:1fr 1fr;.hero{grid-column:1/-1;}.trust{grid-column:1/-1;}.primary{margin:0;}}`;
const Search=styled(Link)`display:flex;align-items:center;gap:16px;min-height:56px;padding:15px;border:1px solid var(--st-line);border-radius:16px;background:var(--st-surface);font-size:14px;svg{width:20px;color:var(--st-gold);}`;
const Trust=styled.div`min-height:92px;padding:16px;border:1px solid var(--st-accent-line);border-radius:16px;background:var(--st-surface);strong{font-size:10px;font-weight:600;letter-spacing:1.2px;color:var(--st-gold);}p{font-size:14px;line-height:20px;margin-top:12px;}`;
const Picks=styled.section`margin-top:8px;.heading{display:flex;align-items:end;justify-content:space-between;margin:0 0 16px;}.kicker{font-size:10px;letter-spacing:1.1px;font-weight:600;color:var(--st-gold);}h2{font:500 26px/30px 'Cormorant Garamond',serif;margin-top:5px;}.all{font-size:12px;color:var(--st-gold);padding:12px 0;}.rail{display:grid;grid-auto-flow:column;grid-auto-columns:286px;gap:16px;overflow:auto;margin-right:-16px;padding-right:16px;scroll-snap-type:x mandatory;scrollbar-width:none;}.rail>article{scroll-snap-align:start;}.preview-note{font-size:11px;line-height:17px;color:var(--st-muted);margin:12px 0;}@media(min-width:850px){margin-top:28px;.rail{grid-auto-columns:calc((100% - 48px)/4);margin-right:0;padding-right:0;}}`;
const StudioLink=styled(Link)`display:flex;align-items:center;justify-content:space-between;gap:16px;margin-top:16px;padding:16px;min-height:120px;border:1px solid var(--st-accent-line);border-radius:16px;background:var(--st-accent);strong{font-size:11px;letter-spacing:1.1px;color:var(--st-gold);font-weight:600;}h2{font:500 26px/30px 'Cormorant Garamond',serif;margin-top:8px;}p{font-size:14px;line-height:20px;color:var(--st-muted);margin-top:4px;}svg{width:22px;flex-shrink:0;}`;
export function Home(){const{studios,loading,error,reload}=useStudios();return <Root><Wrap><Intro><Hero className="hero" data-figma-node="8:2"><img className="art" src="/figma/galaxy-header.svg" width="358" height="230" alt=""/><div className="copy"><h1>Discover your<br/>Korean fortune.</h1><p>A local reader. Your language.</p></div></Hero><ButtonLink className="primary" to="/search">Find a reading</ButtonLink><Search to="/search"><MagnifyingGlassIcon/>Seoul · Any date · English</Search><Trust className="trust"><strong>BOOK WITH CONFIDENCE</strong><p>Clear session details. Your language.</p></Trust></Intro><Picks><div className="heading"><div><span className="kicker">EDITOR’S PICKS</span><h2>Find your reading</h2></div><Link className="all" to="/experiences">View all</Link></div>{error?<Notice role="alert">{error} <button onClick={reload}>Retry</button></Notice>:loading?<div className="rail" aria-busy="true" aria-label="Loading readings">{[0,1,2].map(n=><article key={n} style={{height:338,borderRadius:16,background:'var(--st-surface)'}}/>)}</div>:studios.length?<div className="rail">{studios.slice(0,6).map(s=><ExperienceCard key={s.id} studio={s}/>)}</div>:<Empty title="Readings are on their way" body="We’re preparing our collection of local readers." to="/learn" action="Learn about Saju"/>}{studios.some(s=>s.is_mock)&&<p className="preview-note">Preview collection. Sample studios cannot accept reservations.</p>}</Picks><StudioLink to="/studio"><div><strong>ORACLE STUDIO</strong><h2>Your next chapter</h2><p>Daily flow · Connection · Korean name</p></div><ArrowRightIcon/></StudioLink></Wrap></Root>;}
