import { Link } from 'react-router-dom';
import { styled } from 'styled-components';
import { ArrowRightIcon, ArrowUpRightIcon, HeartIcon, BriefcaseIcon, SparklesIcon, MapPinIcon, ChatBubbleLeftRightIcon, GlobeAltIcon } from '@heroicons/react/24/outline';
import StarfieldSection from '../components/starfield_section';
import { useStudios } from '../product/data';
import { Box, ButtonLink, Eyebrow, ExperienceCard, InlineLink, Lead, Notice, Rail, Section, SectionTop, Wrap } from '../product/ui';
const Hero=styled(StarfieldSection)`border-radius:26px;color:white;min-height:420px;padding:38px 26px 70px;background:#11101d;>canvas{opacity:.55;}@media(min-width:800px){padding:58px 52px 72px;min-height:444px;}h1{font-family:'Cormorant Garamond',serif;font-size:clamp(48px,7vw,80px);line-height:.97;font-weight:500;letter-spacing:-2px;margin:25px 0 18px;max-width:600px;}h1 em{color:#d6caff;font-style:italic;}p{font-size:14px;line-height:1.7;color:#e2deee;max-width:380px;}a{margin-top:24px;background:#d9cdf7;color:#211933;font-size:13px;} .tag{font-size:9px;letter-spacing:1.5px;text-transform:uppercase;color:#d6caff;display:flex;align-items:center;gap:6px;svg{width:14px;}}.pillars{position:absolute;right:44px;bottom:76px;border:1px solid #ffffff30;border-radius:18px;background:#1e172ab3;backdrop-filter:blur(10px);padding:22px;width:280px;display:none;}.pillars strong{font-family:'Cormorant Garamond',serif;font-size:24px;display:block;margin-bottom:8px;}.pillars div{display:flex;gap:8px;margin-top:20px;}.pillars span{border:1px solid #ffffff30;border-radius:30px;padding:8px 11px;font-size:10px;}@media(min-width:1000px){.pillars{display:block;}}@media(max-width:500px){>canvas{opacity:.3;}h1{font-size:53px;}p{max-width:280px;}}`;
const Root=styled.div`background:var(--st-paper);padding:18px 0 20px;`;
const IntroBar=styled.div`display:flex;align-items:center;justify-content:space-between;margin:0 0 14px;font-size:11px;color:var(--st-muted);span{display:flex;gap:5px;align-items:center;}svg{width:13px;}a{font-weight:600;color:var(--st-ink);}`;
const TopicGrid=styled.div`display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;@media(max-width:650px){grid-template-columns:repeat(2,minmax(0,1fr));}`;
const TopicCard=styled(Link)<{$tone:string}>`display:block;background:${p=>p.$tone};border-radius:18px;padding:20px;min-height:170px;position:relative;overflow:hidden;transition:transform .2s;&:hover{transform:translateY(-3px);} .big{width:36px;height:36px;margin-bottom:25px;stroke-width:1.1;}h3{font-size:16px;letter-spacing:-.3px;font-weight:650;margin-bottom:5px;}p{font-size:11px;color:#575563;line-height:1.5;}.arrow{position:absolute;right:16px;top:17px;width:16px;opacity:.5;}@media(max-width:650px){min-height:165px;padding:18px;}`;
const Matcher=styled.div`border:1px solid #d3ccdf;border-radius:20px;padding:24px;background:#eee8f8;display:flex;align-items:center;justify-content:space-between;gap:24px;h2{font-family:'Cormorant Garamond',serif;font-size:32px;line-height:1.1;margin:8px 0;color:#262137;}p{font-size:13px;line-height:1.55;color:#625c71;}a{flex-shrink:0;}@media(max-width:650px){align-items:flex-start;flex-direction:column;gap:18px;a{width:100%;}}`;
const MiniGrid=styled.div`display:grid;grid-template-columns:repeat(3,1fr);gap:14px;h3{font-size:15px;font-weight:650;margin:14px 0 7px;}p{font-size:12px;line-height:1.65;color:var(--st-muted);}svg{width:24px;stroke-width:1.3;}@media(max-width:650px){grid-template-columns:1fr;>div{display:grid;grid-template-columns:36px 1fr;gap:0 12px;padding:17px 0;border-bottom:1px solid var(--st-line);}svg{grid-row:1/3;margin-top:12px;}h3{margin:8px 0;}}`;
const Guide=styled(Link)`display:flex;gap:20px;border-top:1px solid var(--st-line);padding:20px 0;align-items:center;.number{font-family:'Cormorant Garamond',serif;font-size:34px;color:#a69eac;}h3{font-size:16px;font-weight:600;margin:0 0 5px;}p{font-size:12px;color:var(--st-muted);}svg{width:20px;margin-left:auto;flex-shrink:0;}`;
export function Home(){const{studios,loading,error,reload}=useStudios();return <Root><Wrap><IntroBar><span><MapPinIcon/>Seoul, South Korea</span><Link to="/learn">New to Saju? Start here ↗</Link></IntroBar><Hero hero><div className="tag"><SparklesIcon/>A different way to discover Korea</div><h1>A little Seoul.<br/><em>A little soul.</em></h1><p>Meet a local Saju reader. Explore the stories in your birth chart, in a language you understand.</p><ButtonLink to="/experiences">Find your experience<ArrowRightIcon/></ButtonLink><div className="pillars"><strong>Your story. Four pillars.</strong><p>A Korean tradition of reading your year, month, day and hour of birth.</p><div>{['Year','Month','Day','Hour'].map(x=><span key={x}>{x}</span>)}</div></div></Hero>
<Section><SectionTop><div><Eyebrow>Follow your curiosity</Eyebrow><h2>What’s on your mind?</h2><p>You don’t need to know Saju to find your way in.</p></div></SectionTop><TopicGrid>{[{slug:'love',title:'Love & connection',text:'Relationships, chemistry, and you.',tone:'#f2dfe7',Icon:HeartIcon},{slug:'career',title:'Your next chapter',text:'Work, purpose, a change of direction.',tone:'#e3e9dd',Icon:BriefcaseIcon},{slug:'first-reading',title:'Meet yourself',text:'Your first look at the four pillars.',tone:'#e9e2f4',Icon:SparklesIcon},{slug:'together',title:'Better together',text:'A different kind of date in Seoul.',tone:'#f2e7ce',Icon:ChatBubbleLeftRightIcon}].map(t=><TopicCard key={t.slug} to={`/learn/${t.slug}`} $tone={t.tone}><t.Icon className="big"/><ArrowUpRightIcon className="arrow"/><h3>{t.title}</h3><p>{t.text}</p></TopicCard>)}</TopicGrid></Section>
<Matcher><div><Eyebrow>Made for your kind of curious</Eyebrow><h2>Not sure where to begin?</h2><p>Three little questions. A reading experience that fits your trip.</p></div><ButtonLink to="/find-my-reading">Find my reading<ArrowRightIcon/></ButtonLink></Matcher>
<Section><SectionTop><div><Eyebrow>Meet the local side of Seoul</Eyebrow><h2>Make room for a little discovery</h2></div><Link to="/experiences">View all<ArrowRightIcon/></Link></SectionTop>{error?<Notice role="alert">{error} <button onClick={reload}>Retry</button></Notice>:loading?<Lead>Finding experiences…</Lead>:<Rail>{studios.slice(0,6).map(s=><ExperienceCard key={s.id} studio={s}/>)}</Rail>}{studios.length>0&&studios.every(s=>s.is_mock)&&<p style={{fontSize:11,color:'var(--st-muted)',marginTop:8}}>Preview collection: sample studios and illustrative photos. Reservations are not live for these listings.</p>}</Section>
<Section style={{borderTop:'1px solid var(--st-line)'}}><SectionTop><div><Eyebrow>Culture, without the guesswork</Eyebrow><h2>Your first reading, made easier.</h2></div></SectionTop><MiniGrid><div><MapPinIcon/><h3>Find a reader that fits</h3><p>Compare neighborhoods, topics, prices, and session lengths.</p></div><div><GlobeAltIcon/><h3>Know how you’ll communicate</h3><p>See whether the reader speaks your language or uses AI interpretation.</p></div><div><SparklesIcon/><h3>Arrive with a little confidence</h3><p>Know what to bring, what to ask, and what to expect.</p></div></MiniGrid></Section>
<Section><SectionTop><div><Eyebrow>The SajuTeller field guide</Eyebrow><h2>A little context goes a long way.</h2></div><InlineLink to="/learn">All guides<ArrowRightIcon/></InlineLink></SectionTop>{[['01','first-reading','Saju, without the jargon','The four pillars, explained in a few minutes.'],['02','before-you-go','Before you meet your reader','Birth time, language, and questions worth bringing.'],['03','together','Make it a Seoul story','A solo adventure, a date, or a moment with friends.']].map(([n,slug,title,desc])=><Guide to={`/learn/${slug}`} key={slug}><span className="number">{n}</span><div><h3>{title}</h3><p>{desc}</p></div><ArrowUpRightIcon/></Guide>)}</Section>
<Box $tone="#e7eddf"><Eyebrow>For local Saju businesses</Eyebrow><h2 style={{fontFamily:'Cormorant Garamond',fontSize:30,marginTop:9}}>Your next guest could come from anywhere.</h2><p>Help curious travelers discover your practice.</p><InlineLink to="/host">Partner with SajuTeller<ArrowRightIcon/></InlineLink></Box></Wrap></Root>;}
