import { useEffect, useMemo, useRef, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { StreamChat, type Channel as StreamChannel } from 'stream-chat';
import { Chat, Channel, MessageList, MessageInput, Window, Streami18n } from 'stream-chat-react';
import 'stream-chat-react/dist/css/v2/index.css';
import { ArrowLeftIcon, ChatBubbleLeftRightIcon, ChevronRightIcon } from '@heroicons/react/24/outline';
import { styled } from 'styled-components';
import { supabase } from '../supabase';
import { useI18n } from '../i18n/i18n';
import { Button, ButtonLink, Notice, Page, Wrap } from '../product/ui';
type ChatSession={apiKey:string;token:string;user:{id:string;name:string};channelType:string;channelId?:string};
class ChatError extends Error { code:string;constructor(code:string){super(code);this.code=code;} }
async function session(studioId?:string,language?:string):Promise<ChatSession>{
 const{data,error}=await supabase.functions.invoke('business-chat',{body:studioId?{studioId,language}:{}});
 if(error){let code='chat_unavailable';try{const payload=await error.context?.json();code=payload?.code||code;}catch{/* Transport errors use the generic state. */}throw new ChatError(code);}
 return data as ChatSession;
}
const Inbox=styled.div`display:grid;gap:12px;.conversation{width:100%;display:flex;align-items:center;gap:14px;background:var(--st-surface);border:1px solid var(--st-line);border-radius:18px;padding:16px;text-align:left;color:var(--st-ink);cursor:pointer;}.avatar{width:48px;height:48px;display:grid;place-items:center;background:var(--st-accent);border-radius:50%;color:var(--st-gold);flex:none;font-size:21px;}.copy{flex:1;min-width:0;}.copy strong{font-size:14px;display:block;margin-bottom:6px;}.copy p{font-size:12px;color:var(--st-muted);white-space:nowrap;overflow:hidden;text-overflow:ellipsis;}.conversation svg{width:18px;flex:none;}.unread{width:8px;height:8px;background:var(--st-gold);border-radius:50%;}.empty{padding:40px 0;display:grid;gap:20px;text-align:center;justify-items:center;}.empty>svg{width:52px;height:52px;color:var(--st-gold);}.empty h2{font-size:24px;}.empty p{font-size:14px;color:var(--st-muted);}`;
const Room=styled.div`height:100dvh;display:flex;flex-direction:column;min-width:0;overflow:hidden;background:var(--st-paper);.demo-banner{padding:10px 16px;background:var(--st-surface);border-bottom:1px solid var(--st-line);font-size:11px;line-height:1.5;color:var(--st-muted);}.prompts{display:flex;gap:8px;overflow-x:auto;padding-top:8px;padding-bottom:2px;}.demo-banner button{color:var(--st-gold);background:var(--st-accent);border:1px solid var(--st-accent-line);border-radius:999px;min-height:36px;padding:7px 12px;font-size:11px;white-space:nowrap;cursor:pointer;}.demo-banner button:disabled{opacity:.5;}.room-header{height:68px;flex:none;display:flex;align-items:center;gap:14px;padding:12px 16px;border-bottom:1px solid var(--st-line);}.room-header a{width:44px;height:44px;border-radius:50%;background:var(--st-elevated);display:grid;place-items:center;}.room-header svg{width:21px;}.room-header h1{font-size:16px;font-weight:600;}.room-header p{font-size:11px;color:var(--st-muted);margin-top:5px;}.chat-container{flex:1;min-height:0;overflow:hidden;}.str-chat{height:100%;font-family:Inter,system-ui,sans-serif;--str-chat__primary-color:var(--st-gold);--str-chat__active-primary-color:var(--st-gold);--str-chat__background-color:var(--st-paper);--str-chat__secondary-background-color:var(--st-surface);--str-chat__primary-surface-color:var(--st-accent);--str-chat__text-color:var(--st-ink);--str-chat__secondary-text-color:var(--st-muted);--str-chat__message-bubble-background-color:var(--st-elevated);--str-chat__own-message-bubble-background-color:var(--st-accent);}.str-chat__channel,.str-chat__container{height:100%;min-width:0;}.str-chat__message-input{padding-bottom:max(12px,env(safe-area-inset-bottom));}.str-chat__message-list{padding-inline:12px;}`;
export default function Messages(){
 const{t,language}=useI18n();const[params,setParams]=useSearchParams();const studioId=params.get('studio')||undefined;const channelId=params.get('channel');const[client,setClient]=useState<StreamChat|null>(null);const[channels,setChannels]=useState<StreamChannel[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[retry,setRetry]=useState(0);
 const [replyFailed,setReplyFailed]=useState<{studioId:string;messageId:string}|null>(null);const [replyBusy,setReplyBusy]=useState(false);
 const locale=useRef(language);locale.current=language;
 async function demoReply(studio:string,messageId:string){setReplyBusy(true);try{const {error}=await supabase.functions.invoke('business-chat',{body:{action:'demo_reply',studioId:studio,messageId,language:locale.current}});if(error)throw error;setReplyFailed(null);}catch{setReplyFailed({studioId:studio,messageId});}finally{setReplyBusy(false);}}
 const replyRef=useRef(demoReply);replyRef.current=demoReply;
 const updateParams=useRef(setParams);updateParams.current=setParams;
 const i18n=useMemo(()=>new Streami18n({language:language==='zh'?'zh':language}),[language]);
 useEffect(()=>{let active=true;let connection:StreamChat|undefined;let unsubscribe:(()=>void)|undefined;
 setLoading(true);setError('');setClient(null);setReplyFailed(null);setChannels([]);
 void(async()=>{try{const result=await session(studioId,locale.current);const c=new StreamChat(result.apiKey);connection=c;await c.connectUser(result.user,async()=>{const refreshed=await session();if(refreshed.user.id!==result.user.id)throw new Error('Session changed');return refreshed.token;});if(!active){await c.disconnectUser();return;}
 const load=async()=>{const list=await c.queryChannels({type:result.channelType,members:{$in:[result.user.id]}},[{last_message_at:-1}],{limit:30,state:true,watch:true});if(result.channelId&&!list.some(ch=>ch.id===result.channelId)){const selected=await c.queryChannels({type:result.channelType,id:result.channelId,members:{$in:[result.user.id]}},{},{limit:1,state:true,watch:true});list.unshift(...selected);}if(active)setChannels(list);};await load();if(!active)return;setClient(c);
 if(result.channelId)updateParams.current({channel:result.channelId,...(studioId?{studio:studioId}:{})},{replace:true});
 const sub=c.on(e=>{if(e.type==='message.new'&&e.user?.id===result.user.id&&e.message?.id&&e.cid){const room=c.activeChannels[e.cid];const data=room?.data as Record<string,unknown>|undefined;if(data?.is_demo&&typeof data.studio_id==='string')void replyRef.current(data.studio_id,e.message.id);}
 if(['message.new','notification.message_new','notification.added_to_channel','notification.removed_from_channel'].includes(e.type))void load().catch(()=>{if(active)setError('chat_unavailable');});});unsubscribe=()=>sub.unsubscribe();
 }catch(e){if(active)setError(e instanceof ChatError?e.code:'chat_unavailable');}finally{if(active)setLoading(false);}})();
 return()=>{active=false;unsubscribe?.();void connection?.disconnectUser();};
 // Reconnect when the business changes; room selection alone reuses the connection.
 },[retry,studioId]);
 const current=channels.find(c=>c.id===channelId);
 if(current&&client){const data=current.data as Record<string,unknown>;const isDemo=!!data?.is_demo;const name=String(data?.name||t('Business conversation'));return <Room><header className="room-header"><Link to="/messages" aria-label={t('Back to messages')}><ArrowLeftIcon/></Link><div><h1>{name}</h1><p>{t(isDemo?'Demo · Automated host':'Business conversation')}</p></div></header>{isDemo&&<div className="demo-banner"><p>{t('Demo conversation. No real booking or payment.')}</p><div className="prompts">{['How much is a session?','Which languages are available?','What should I prepare?'].map(prompt=><button key={prompt} disabled={replyBusy} onClick={()=>{void current.sendMessage({text:t(prompt)}).catch(()=>setError('chat_unavailable'));}}>{t(prompt)}</button>)}</div>{replyBusy&&<p role="status">{t('Demo host is replying…')}</p>}{replyFailed&&<p role="alert">{t('The demo reply could not be delivered.')} <button disabled={replyBusy} onClick={()=>void demoReply(replyFailed.studioId,replyFailed.messageId)}>{t('Retry')}</button></p>}{error&&<p role="alert">{t('Could not send. Please try again.')} <button onClick={()=>setError('')}>{t('Close')}</button></p>}</div>}<div className="chat-container"><Chat client={client} i18nInstance={i18n} theme="str-chat__theme-dark"><Channel channel={current}><Window><MessageList messageActions={['react','flag','quote']}/><MessageInput focus/></Window></Channel></Chat></div></Room>;}
 const detail=error==='chat_not_configured'?'Business chat is being prepared. Please try again later.':error==='business_unavailable'?'This business is not receiving messages yet.':error==='preview_studio'?'Preview studios cannot receive messages. Choose a live studio when available.':'We couldn’t load your messages. Please try again.';
 return <Page><Wrap><h1>{t('Messages')}</h1>{loading?<p role="status">{t('Loading…')}</p>:error?<><Notice role="alert">{t(detail)}</Notice><Button onClick={()=>setRetry(v=>v+1)}>{t('Try again')}</Button><ButtonLink to="/experiences" $secondary style={{marginTop:12}}>{t('Explore experiences')}</ButtonLink></>:<Inbox>{channels.length?channels.map(c=><button className="conversation" key={c.cid} onClick={()=>setParams({channel:c.id!})}><span className="avatar">{String((c.data as Record<string,unknown>)?.name||'S')[0]}</span><div className="copy"><strong>{String((c.data as Record<string,unknown>)?.name||t('Business conversation'))}</strong><p>{c.state.messages.at(-1)?.text||t('Chat with the business')}</p></div>{c.countUnread()>0&&<span className="unread" aria-label={t('Unread messages')}/>}<ChevronRightIcon/></button>):<div className="empty"><ChatBubbleLeftRightIcon/><h2>{t('No conversations yet')}</h2><p>{t('Open an experience and choose “Chat with the business” to ask a question.')}</p><ButtonLink to="/experiences">{t('Explore experiences')}</ButtonLink></div>}</Inbox>}</Wrap></Page>;
}
