import { useState } from "react";
import { Link, useNavigate, useSearchParams } from "react-router-dom";
import { Card, Divider, Form, Error as ErrorText, Input, LogoImage, Page, Switcher, Wrapper, GoogleButton, KakaoButton, LanguageSelector, Title } from "../components/auth_components";
import { useI18n } from "../i18n/i18n";
import { safeReturn } from "../product/plans";
import { supabase } from "../supabase";

export function CreateAccount(){
 const [params]=useSearchParams();const destination=safeReturn(params.get("next"));const [confirmation,setConfirmation]=useState(false);
 const {t}=useI18n();const navigate=useNavigate();const [isLoading,setLoading]=useState(false);const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [confirmPassword,setConfirmPassword]=useState('');const [error,setError]=useState('');
 const onGoogle=async()=>{localStorage.setItem('returnUrl',destination);const {error}=await supabase.auth.signInWithOAuth({provider:'google'});if(error)setError(error.message);};
 const onKakao=async()=>{localStorage.setItem('returnUrl',destination);const {error}=await supabase.auth.signInWithOAuth({provider:'kakao'});if(error)setError(error.message);};
 const onSubmit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setError('');if(isLoading||!email||!password||!confirmPassword)return;if(password!==confirmPassword){setError('Passwords do not match');return;}try{setLoading(true);localStorage.setItem('returnUrl',destination);const {data,error}=await supabase.auth.signUp({email,password,options:{emailRedirectTo:window.location.origin+'/auth-callback'}});if(error)setError(error.message);else if(data.session)navigate(destination);else setConfirmation(true);}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setLoading(false);}};
 return <Page><LanguageSelector/><Card><LogoImage/><Wrapper><div style={{textAlign:'center'}}><Title>Create your account</Title><p style={{margin:'8px 0 4px',color:'#6b7280',fontSize:14,lineHeight:1.5}}>Request a visit, follow its status, or introduce your Saju practice.</p></div>{confirmation?<p role="status" style={{lineHeight:1.7,padding:20,background:'#e9e2f4',borderRadius:14}}>Check your email for a confirmation link. After confirming, return here to sign in and continue your plans.</p>:<Form onSubmit={onSubmit}><Input aria-label="Email address" autoComplete="email" name="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder={t('email')} type="email" required/><Input aria-label="Password" minLength={6} autoComplete="new-password" name="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder={t('password')} type="password" required/><Input aria-label="Confirm password" minLength={6} autoComplete="new-password" name="confirmPassword" value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} placeholder={t('confirmPassword')} type="password" required/><Input type="submit" value={isLoading?t('loading'):t('createAccount')}/></Form>}<Divider>{t('or')}</Divider><div style={{display:'flex',flexDirection:'column',gap:10}}><GoogleButton onClick={onGoogle}/><KakaoButton onClick={onKakao}/></div>{error?<ErrorText>{error}</ErrorText>:null}<Switcher>{t('alreadyHaveAccount')} <Link to={"/sign-in?next="+encodeURIComponent(destination)}>{t('logInHere')} →</Link></Switcher></Wrapper></Card></Page>;
}
