// Deliberately scripted, visibly automated responses; never confirm a real appointment.
type Language = 'en'|'ko'|'zh'|'ja'|'es';
const copy: Record<Language, { welcome:string; price:string; language:string; place:string; time:string; prepare:string; general:string; suffix:string }> = {
 en: {welcome:'Hello! I’m the automated demo host. Ask about pricing, languages, availability, or what to prepare.',price:'The sample session starts at {price} KRW and lasts {duration} minutes, for up to {guests} guest(s).',language:'You can try this demo conversation in English, Korean, Mandarin Chinese, Japanese, or Spanish.',place:'Our illustrative location is {area}, Seoul. This is a fictional studio, so there is no real venue to visit.',time:'For the demo, imagine a 2 pm or 4 pm session. These are sample times only; no appointment can be confirmed.',prepare:'For a Saju reading, prepare your birth date and time if known, plus one or two questions. For tarot, just bring a question. You don’t need to share private birth details in this chat.',general:'I can explain the sample price, languages, location, availability, or how to prepare. What would you like to try?',suffix:'Demo · Automated reply. No real booking or payment.'},
 ko: {welcome:'안녕하세요! 자동 응답 데모 호스트입니다. 가격, 언어, 예약 가능 시간, 준비물에 대해 물어보세요.',price:'예시 상담은 {price}원부터이며, {duration}분 동안 최대 {guests}명이 참여할 수 있어요.',language:'영어, 한국어, 중국어, 일본어, 스페인어로 데모 대화를 체험할 수 있어요.',place:'예시 위치는 서울 {area}입니다. 가상의 상담소이므로 실제 방문할 장소는 없어요.',time:'데모에서는 오후 2시 또는 4시 상담을 가정해 볼 수 있어요. 예시 시간이며 실제 예약은 확정되지 않아요.',prepare:'사주 상담에는 생년월일과 알고 있다면 태어난 시간, 질문 한두 가지를 준비하세요. 타로는 질문만 있으면 돼요. 이 채팅에 개인 출생 정보를 공유할 필요는 없어요.',general:'예시 가격, 언어, 위치, 가능 시간, 준비물을 안내할 수 있어요. 무엇을 체험해 볼까요?',suffix:'데모 · 자동 응답. 실제 예약이나 결제는 이루어지지 않아요.'},
 zh: {welcome:'你好！我是自动回复的演示接待员。可以询问价格、语言、预约时间或需要准备什么。',price:'示例解读价格为 {price} 韩元起，时长 {duration} 分钟，最多 {guests} 人。',language:'你可以使用英语、韩语、普通话、日语或西班牙语体验演示对话。',place:'示例位置位于首尔 {area}。这是一家虚构工作室，没有可实际到访的场所。',time:'演示中可以假设下午2点或4点的体验。这些仅为示例时间，无法确认实际预约。',prepare:'四柱解读可准备出生日期、已知的出生时间和一两个问题。塔罗只需准备问题。无需在聊天中分享私密出生信息。',general:'我可以介绍示例价格、语言、位置、预约时间或准备事项。你想了解哪一项？',suffix:'演示 · 自动回复。不会产生真实预约或付款。'},
 ja: {welcome:'こんにちは！自動応答のデモホストです。料金、言語、空き時間、準備するものについて聞いてみてください。',price:'サンプル鑑定は {price} ウォンから、所要時間は {duration} 分、最大 {guests} 名です。',language:'英語、韓国語、中国語、日本語、スペイン語でデモ会話を体験できます。',place:'イメージ上の所在地はソウルの {area} です。架空の鑑定所のため、実際に訪問できる場所はありません。',time:'デモでは午後2時または4時の鑑定を想定できます。サンプルの時間であり、実際の予約は確定できません。',prepare:'四柱推命には生年月日、分かれば出生時刻、質問を一つか二つご用意ください。タロットは質問だけで大丈夫です。このチャットで個人の出生情報を共有する必要はありません。',general:'サンプル料金、言語、場所、空き時間、準備についてご案内できます。何を試してみますか？',suffix:'デモ · 自動応答。実際の予約や決済は行われません。'},
 es: {welcome:'¡Hola! Soy el anfitrión automático de demostración. Pregúntame por precios, idiomas, disponibilidad o qué preparar.',price:'La sesión de ejemplo cuesta desde {price} KRW, dura {duration} minutos y admite hasta {guests} persona(s).',language:'Puedes probar esta conversación en inglés, coreano, chino mandarín, japonés o español.',place:'La ubicación ilustrativa es {area}, Seúl. Este centro es ficticio; no hay un lugar real que visitar.',time:'Para la demo, imagina una sesión a las 14:00 o a las 16:00. Son horas de ejemplo; no se puede confirmar ninguna cita real.',prepare:'Para Saju, prepara tu fecha y hora de nacimiento si la conoces, y una o dos preguntas. Para tarot, basta una pregunta. No necesitas compartir datos privados de nacimiento en este chat.',general:'Puedo explicar el precio de ejemplo, los idiomas, la ubicación, la disponibilidad o cómo prepararte. ¿Qué te gustaría probar?',suffix:'Demo · Respuesta automática. Sin reservas ni pagos reales.'},
};
export function demoText(locale:unknown, studio:{base_price:number;min_duration_minutes:number;max_guests:number;neighborhood:string}, text?:string) {
 const lang=typeof locale==='string'&&locale in copy?locale as Language:'en';const c=copy[lang];
 const q=(text||'').toLowerCase();
 const key=text===undefined?'welcome':/price|cost|how much|가격|얼마|费用|价格|多少钱|料金|いくら|precio|cuesta/.test(q)?'price':/language|english|korean|chinese|japanese|spanish|언어|영어|语言|中文|言語|日本語|idioma/.test(q)?'language':/where|location|address|어디|위치|位置|地址|場所|どこ|dónde|ubicación/.test(q)?'place':/available|availability|book|tomorrow|appointment|예약|시간|가능|预约|空き|予約|disponib|reserva|mañana/.test(q)?'time':/prepare|bring|birth|준비|생년|准备|出生|準備|持ち|prepar|llevar|nacimiento/.test(q)?'prepare':'general';
 return c[key].replace('{price}',studio.base_price.toLocaleString('en-US')).replace('{duration}',String(studio.min_duration_minutes)).replace('{guests}',String(studio.max_guests)).replace('{area}',studio.neighborhood)+'\n\n'+c.suffix;
}
