import { useEffect, useRef, useState } from 'react';
import { CheckIcon, XMarkIcon } from '@heroicons/react/24/outline';
import { styled } from 'styled-components';
import { useI18n, type Language } from '../i18n/i18n';
const choices: { id: Language; name: string; flag: string }[] = [
  { id:'en', name:'English', flag:'🇺🇸' }, { id:'ko', name:'한국어', flag:'🇰🇷' },
  { id:'zh', name:'简体中文', flag:'🇨🇳' }, { id:'ja', name:'日本語', flag:'🇯🇵' }, { id:'es', name:'Español', flag:'🇪🇸' },
];
const Toggle=styled.button`width:44px;height:44px;border:0;border-radius:50%;background:var(--st-elevated);box-shadow:inset 0 0 0 1px #b8acbf14;display:grid;place-items:center;cursor:pointer;span{font-size:24px;line-height:1;}`;
const Sheet=styled.dialog`width:min(382px,calc(100% - 32px));padding:24px;border:1px solid var(--st-line);border-radius:24px;background:var(--st-surface);color:var(--st-ink);margin:auto;max-height:85dvh;overflow:auto;&::backdrop{background:#08040dbb;backdrop-filter:blur(5px);}header{display:flex;align-items:center;justify-content:space-between;margin-bottom:16px;}h2{font-size:22px;font-weight:600;}button{cursor:pointer;color:inherit;}header button{display:grid;place-items:center;width:44px;height:44px;border:0;border-radius:50%;background:var(--st-elevated);}svg{width:20px;height:20px;}.language-option{width:100%;min-height:60px;display:flex;align-items:center;gap:16px;padding:12px;border:0;border-radius:14px;background:none;text-align:left;font-size:16px;}.language-option[aria-pressed=true]{background:var(--st-accent);}.flag{font-size:25px;}.language-option svg{margin-left:auto;color:var(--st-gold);}`;
export default function LocaleSelector(){const{language,setLanguage,t}=useI18n();const[open,setOpen]=useState(false);const ref=useRef<HTMLDialogElement>(null);const current=choices.find(c=>c.id===language)!;useEffect(()=>{if(!open)return;const d=ref.current;const old=document.body.style.overflow;d?.showModal();document.body.style.overflow='hidden';return()=>{d?.close();document.body.style.overflow=old;};},[open]);return <><Toggle aria-label={`${t('Language')}: ${current.name}`} aria-haspopup="dialog" onClick={()=>setOpen(true)}><span aria-hidden="true">{current.flag}</span></Toggle>{open&&<Sheet ref={ref} aria-labelledby="language-title" onCancel={()=>setOpen(false)} onClick={e=>{if(e.target===ref.current){const r=ref.current!.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)setOpen(false);}}}><header><h2 id="language-title">{t('Choose your language')}</h2><button aria-label={t('Close')} onClick={()=>setOpen(false)}><XMarkIcon/></button></header>{choices.map(c=><button key={c.id} className="language-option" lang={c.id==='zh'?'zh-Hans':c.id} aria-pressed={c.id===language} onClick={()=>{setLanguage(c.id);setOpen(false);}}><span className="flag" aria-hidden="true">{c.flag}</span>{c.name}{c.id===language&&<CheckIcon/>}</button>)}</Sheet>}</>;}
