import { useCallback, useEffect, useState } from 'react';
import { supabase } from '../supabase';
export type LanguageSupport = { language_code:string; support_type:string };
export type Studio = { id:string; slug:string; name:string; name_ko:string; tagline:string; description:string; neighborhood:string; city:string; address_line1:string; nearest_station:string; station_walk_minutes:number; base_price:number; min_duration_minutes:number; max_guests:number; min_age:number; specialties:string[]; modalities:string[]; ai_interpretation_available:boolean; wheelchair_accessible:boolean; average_rating:number; review_count:number; is_mock:boolean; verified:boolean; is_featured:boolean; studio_images:{image_url:string;alt_text:string;sort_order:number}[]; studio_languages:LanguageSupport[] };
export type Service = {id:string;studio_id:string;name:string;description:string;duration_minutes:number;price:number;max_guests:number;requires_birth_date:boolean;birth_time_recommended:boolean};
export type Review = {id:string;reviewer_display_name:string;rating:number;body:string;title:string;is_mock:boolean;verified_booking:boolean};
export const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'KRW',maximumFractionDigits:0}).format(n);
export const languageNames:Record<string,string>={en:'English',ko:'Korean',zh:'Chinese',ja:'Japanese',es:'Spanish',fr:'French'};
export const supportLabel=(s:string)=>s==='ai_interpreter'?'AI interpretation':s==='native'?'Reader speaks':'Conversational';
export function cover(s:Studio){return [...(s.studio_images||[])].sort((a,b)=>a.sort_order-b.sort_order)[0];}
export const studioSelect='id,slug,name,name_ko,tagline,description,neighborhood,city,address_line1,nearest_station,station_walk_minutes,base_price,min_duration_minutes,max_guests,min_age,specialties,modalities,ai_interpretation_available,wheelchair_accessible,average_rating,review_count,is_mock,verified,is_featured,studio_images(image_url,alt_text,sort_order),studio_languages(language_code,support_type)';
let cached:Studio[]|null=null;
let pending:Promise<Studio[]>|null=null;
async function getStudios(){
 if(cached)return cached;
 if(!pending)pending=(async()=>{const {data,error}=await supabase.from('saju_studios').select(studioSelect).eq('status','active').order('is_featured',{ascending:false}).order('name');if(error)throw error;cached=(data||[]) as unknown as Studio[];return cached;})().finally(()=>{pending=null;});
 return pending;
}
export function useStudios(){const [studios,setStudios]=useState<Studio[]>(cached||[]);const [loading,setLoading]=useState(!cached);const [error,setError]=useState('');const [retry,setRetry]=useState(0);useEffect(()=>{let alive=true;getStudios().then(v=>{if(alive){setStudios(v);setError('');}}).catch(()=>{if(alive)setError('We couldn’t load experiences. Please try again.');}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;};},[retry]);return{studios,loading,error,reload:()=>{setLoading(true);setRetry(x=>x+1);}};}
const savedKey='sajuteller-saved-v1';
function readSaved():string[]{try{const v=JSON.parse(localStorage.getItem(savedKey)||'[]');return Array.isArray(v)?v.filter(x=>typeof x==='string'):[];}catch{return[];}}
export function useSaved(){const [saved,setSaved]=useState(readSaved);useEffect(()=>{const update=()=>setSaved(readSaved());window.addEventListener('storage',update);window.addEventListener('sajuteller-saved',update);return()=>{window.removeEventListener('storage',update);window.removeEventListener('sajuteller-saved',update);};},[]);const toggle=useCallback((id:string)=>{const values=readSaved();const next=values.includes(id)?values.filter(x=>x!==id):[...values,id];try{localStorage.setItem(savedKey,JSON.stringify(next));window.dispatchEvent(new Event('sajuteller-saved'));}catch{setSaved(next);}},[]);return{saved,toggle};}
export function useAccount(){const [account,setAccount]=useState<{id:string;email?:string}|null>(null);const [loading,setLoading]=useState(true);useEffect(()=>{let live=true;supabase.auth.getSession().then(({data})=>{if(live){setAccount(data.session?.user||null);setLoading(false);}});const{data}=supabase.auth.onAuthStateChange((_e,s)=>{if(live){setAccount(s?.user||null);setLoading(false);}});return()=>{live=false;data.subscription.unsubscribe();};},[]);return{account,loading};}
export const topics=[{id:'all',label:'All experiences'},{id:'general',label:'First reading'},{id:'love',label:'Love & connection'},{id:'career',label:'Career & direction'},{id:'compatibility',label:'Together'},{id:'wealth',label:'Money & timing'}];
export function filterStudios(studios:Studio[],params:URLSearchParams){const topic=params.get('topic')||'all';const area=params.get('area')||'';const lang=params.get('language')||'';const budget=Number(params.get('budget'))||Infinity;const q=(params.get('q')||'').toLowerCase().trim();const filtered=studios.filter(s=>(topic==='all'||s.specialties?.includes(topic)||s.modalities?.includes(topic)||(topic==='general'&&s.specialties?.includes('traditional_saju')))&&(!area||s.neighborhood===area)&&(!lang||s.studio_languages?.some(l=>l.language_code===lang))&&s.base_price<=budget&&(!q||[s.name,s.name_ko,s.neighborhood,s.tagline,...(s.specialties||[])].join(' ').toLowerCase().includes(q)));if(params.get('sort')==='price')filtered.sort((a,b)=>a.base_price-b.base_price);if(params.get('sort')==='duration')filtered.sort((a,b)=>a.min_duration_minutes-b.min_duration_minutes);return filtered;}
