import { Link } from 'react-router-dom';
import { styled } from 'styled-components';
import { ArrowRightIcon, HeartIcon, MapPinIcon, SparklesIcon } from '@heroicons/react/24/outline';
import { cover, languageNames, money, supportLabel, useSaved, type Studio } from './data';
export const Wrap=styled.div`width:min(1160px,calc(100% - 40px));margin:0 auto;@media(max-width:600px){width:calc(100% - 32px);}`;
export const Page=styled.div`background:var(--st-paper);color:var(--st-ink);min-height:65vh;padding:32px 0 64px;h1{font-family:'Cormorant Garamond',serif;font-size:clamp(38px,6vw,62px);line-height:1.03;font-weight:600;letter-spacing:-1.5px;margin:10px 0 16px;}h2{font-size:24px;letter-spacing:-.6px;line-height:1.2;font-weight:650;}h3{font-weight:650;line-height:1.35;}p{line-height:1.65;}@media(min-width:800px){padding-top:48px;}`;
export const Eyebrow=styled.div`font-size:10px;font-weight:750;letter-spacing:1.6px;text-transform:uppercase;color:var(--st-muted);display:flex;gap:8px;align-items:center;svg{width:15px;}`;
export const Lead=styled.p`color:var(--st-muted);font-size:15px;max-width:600px;line-height:1.65;margin:0 0 24px;`;
export const Section=styled.section`padding:32px 0;@media(min-width:800px){padding:44px 0;}`;
export const SectionTop=styled.div`display:flex;align-items:flex-end;justify-content:space-between;gap:16px;margin-bottom:20px;h2{font-size:clamp(23px,3vw,30px);line-height:1.2;letter-spacing:-.6px;font-weight:650;margin:5px 0;}p{color:var(--st-muted);font-size:13px;margin-top:6px;line-height:1.5;}a{flex-shrink:0;font-size:12px;font-weight:650;min-height:44px;display:flex;align-items:center;gap:4px;}svg{width:15px;}`;
export const Button=styled.button<{$secondary?:boolean}>`border:1px solid ${p=>p.$secondary?'var(--st-line)':'transparent'};background:${p=>p.$secondary?'transparent':'var(--st-ink)'};color:${p=>p.$secondary?'var(--st-ink)':'white'};border-radius:14px;min-height:48px;padding:12px 20px;font-size:13px;font-weight:650;cursor:pointer;display:inline-flex;align-items:center;justify-content:center;gap:9px;transition:transform .15s,background .15s;svg{width:18px;flex-shrink:0;}&:hover{transform:translateY(-1px);}&:disabled{opacity:.45;cursor:not-allowed;transform:none;}`;
export const ButtonLink=styled(Link)<{$secondary?:boolean}>`border:1px solid ${p=>p.$secondary?'var(--st-line)':'transparent'};background:${p=>p.$secondary?'transparent':'var(--st-ink)'};color:${p=>p.$secondary?'var(--st-ink)':'white'};border-radius:14px;min-height:48px;padding:12px 20px;font-size:13px;font-weight:650;display:inline-flex;align-items:center;justify-content:center;gap:9px;svg{width:18px;flex-shrink:0;}`;
export const InlineLink=styled(Link)`font-size:13px;font-weight:650;display:inline-flex;align-items:center;gap:6px;min-height:44px;svg{width:16px;}`;
export const Box=styled.div<{$tone?:string}>`background:${p=>p.$tone||'white'};border:1px solid var(--st-line);border-radius:20px;padding:22px;min-width:0;h2,h3{margin-bottom:10px;}p{font-size:14px;line-height:1.65;color:var(--st-muted);}p+p{margin-top:12px;}`;
export const Stack=styled.div`display:grid;gap:16px;`;
export const Grid=styled.div`display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:24px;@media(max-width:900px){grid-template-columns:repeat(2,minmax(0,1fr));}@media(max-width:550px){grid-template-columns:1fr;}`;
export const Rail=styled.div`display:grid;grid-auto-flow:column;grid-auto-columns:calc((100% - 48px)/3);gap:24px;overflow-x:auto;scroll-snap-type:x mandatory;padding-bottom:12px;scrollbar-width:thin;> *{scroll-snap-align:start;min-width:0;}@media(max-width:800px){grid-auto-columns:78%;gap:14px;}`;
export const Chip=styled.button<{$active?:boolean}>`white-space:nowrap;border:1px solid ${p=>p.$active?'var(--st-ink)':'var(--st-line)'};background:${p=>p.$active?'var(--st-ink)':'white'};color:${p=>p.$active?'white':'var(--st-ink)'};border-radius:100px;min-height:44px;padding:10px 17px;font-size:12px;font-weight:600;cursor:pointer;`;
export const Chips=styled.div`display:flex;gap:8px;overflow-x:auto;padding:4px 0 12px;scrollbar-width:none;`;
export const Field=styled.label`display:grid;gap:8px;color:var(--st-ink);font-size:12px;font-weight:650;min-width:0;input,select,textarea{width:100%;min-width:0;min-height:48px;padding:12px 14px;border:1px solid var(--st-line);border-radius:12px;background:white;color:var(--st-ink);font-size:16px;}textarea{min-height:110px;resize:vertical;}`;
export const Note=styled.p`font-size:12px!important;color:var(--st-muted);line-height:1.6;margin-top:14px;`;
export const Notice=styled.div`padding:12px 16px;border-radius:12px;background:#eeebf8;color:#57506a;font-size:12px;line-height:1.5;margin-bottom:20px;`;
export const IconBox=styled.div`width:44px;height:44px;border-radius:14px;background:var(--st-lilac);display:flex;align-items:center;justify-content:center;margin-bottom:16px;svg{width:23px;}`;
const Card=styled.article`min-width:0;position:relative;h3{font-size:16px;line-height:1.35;margin:9px 0 6px;font-weight:650;}p{font-size:12px;line-height:1.55;color:var(--st-muted);}a{display:block;}img{width:100%;height:100%;object-fit:cover;transition:transform .3s;}a:hover img{transform:scale(1.04);}.photo{height:220px;border-radius:18px;overflow:hidden;background:#e8e2d8;position:relative;}.sample{position:absolute;left:12px;top:12px;background:#ffffffeb;border-radius:30px;padding:6px 9px;font-size:9px;font-weight:650;letter-spacing:.7px;text-transform:uppercase;}.meta{display:flex;align-items:center;gap:5px;font-size:11px;color:var(--st-muted);margin-top:13px;svg{width:13px;}}.price{margin-top:12px;padding-top:12px;border-top:1px solid var(--st-line);color:var(--st-ink);font-size:12px;}.price strong{font-size:16px;font-weight:650;}.language{font-size:11px;display:flex;align-items:center;gap:5px;margin-top:7px;color:#476b5a;}.fallback{height:100%;display:grid;place-content:center;background:#ded7ed;color:#777083;svg{width:70px;}}@media(max-width:550px){.photo{height:230px;}}`;
const Save=styled.button<{$saved:boolean}>`position:absolute;right:10px;top:10px;z-index:2;width:44px;height:44px;border:0;border-radius:50%;display:grid;place-items:center;background:#fffffff0;color:${p=>p.$saved?'#92517a':'#292534'};cursor:pointer;svg{width:20px;fill:${p=>p.$saved?'currentColor':'none'};}`;
export function ExperienceCard({studio:s}:{studio:Studio}){const {saved,toggle}=useSaved();const photo=cover(s);const language=s.studio_languages?.find(l=>l.language_code==='en')||s.studio_languages?.find(l=>l.language_code!=='ko');return <Card><Link to={`/business/${s.id}`}><div className="photo">{photo?<img src={photo.image_url} alt={s.is_mock?'Illustrative experience photo':photo.alt_text||s.name} loading="lazy" onError={e=>{e.currentTarget.style.display='none';}}/>:<div className="fallback"><SparklesIcon/></div>}{s.is_mock&&<span className="sample">Preview studio</span>}</div><div className="meta"><MapPinIcon/>{s.neighborhood}, {s.city||'Seoul'}<span> / {s.min_duration_minutes} min</span></div><h3>{s.name}</h3><p>{s.tagline}</p>{language&&<div className="language">{supportLabel(language.support_type)} · {languageNames[language.language_code]||language.language_code}</div>}<div className="price">From <strong>{money(s.base_price)}</strong> / person</div></Link><Save $saved={saved.includes(s.id)} onClick={()=>toggle(s.id)} aria-label={`${saved.includes(s.id)?'Unsave':'Save'} ${s.name}`} aria-pressed={saved.includes(s.id)}><HeartIcon/></Save></Card>;}
export function Empty({title,body,to='/experiences',action='Explore experiences'}:{title:string;body:string;to?:string;action?:string}){return <Box><IconBox><SparklesIcon/></IconBox><h2>{title}</h2><p>{body}</p><ButtonLink to={to} style={{marginTop:20}}>{action}<ArrowRightIcon/></ButtonLink></Box>;}
export function LoadingCards(){return <Grid aria-label="Loading experiences" aria-busy="true">{[1,2,3].map(n=><Box key={n} style={{height:320,background:'#eeeae3'}}/>)}</Grid>;}
